version: '3.8'

services:
  # frontend:
  #     image: 853660505909.dkr.ecr.ap-northeast-2.amazonaws.com/springboot:frontend-latest
  #     ports:
  #       - "80:80"
  #     restart: unless-stopped
  #     depends_on:
  #       - backend
  #     networks:
  #       - datastream_monitory-network

  backend:
    image: 853660505909.dkr.ecr.ap-northeast-2.amazonaws.com/springboot:backend-latest
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - datastream_monitory-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: factor2al
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: factor2al
    ports:
      - "3306:3306"
    networks:
      - datastream_monitory-network
    volumes:
      - mysql-data:/var/lib/mysql


networks:
  datastream_monitory-network:
    external: true


volumes:
  mysql-data:
