services:
  monitory-data:
    image: 853660505909.dkr.ecr.ap-northeast-2.amazonaws.com/flink:flink-latest
    ports:
      - "8081:8081"
      - "6123:6123"
    env_file:
      - .env
    networks:
      - datastream_monitory-network

networks:
  datastream_monitory-network:
    external: true
